name: Audit de Sécurité Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  prowler-scan:
    runs-on: ubuntu-latest
    name: Scan AWS avec Prowler
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation et Scan Prowler
        # Image Docker officielle de Prowler pour scanner
        uses: toniblyx/prowler-github-action@master
        with:
          args: aws --services ec2 --region us-east-1 --checks ec2_securitygroup_allow_ingress_from_internet_to_any_port
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}